### ISSUE TITLE
cuda related error when try to run example

### ISSUE THREAD

**Issue by scotthuang1989** [determined-ai/determined#1615]
I try to run this [tutorial](http://192.168.8.101:8080/docs/tutorials/pytorch-mnist-tutorial.html#pytorch-mnist-tutorial). after I start the job with command: `det experiment create const.yaml .`

I see the failed result from WEB UI. the error  log is ( the log repeat 6 times):

> [2020-11-19, 14:08:19] 25f5d319 [PULLING] || image already found, skipping pull phase: docker.io/determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.15-gpu-1def2ee
[2020-11-19, 14:08:20] 25f5d319 [STARTING] || copying files to container: /
[2020-11-19, 14:08:20] 25f5d319 [STARTING] || copying files to container: /
[2020-11-19, 14:08:20] 25f5d319 [STARTING] || copying files to container: /
[2020-11-19, 14:08:20] 25f5d319 [STARTING] || copying files to container: /run/determined/train
[2020-11-19, 14:08:21] 25f5d319 [STARTING] || copying files to container: /run/determined/workdir
[2020-11-19, 14:08:21] 25f5d319 [STARTING] || copying files to container: /
[2020-11-19, 14:08:21] 25f5d319 [STARTING] || copying files to container: /
[2020-11-19, 14:08:22] 25f5d319 [TERMINATED] || container failed with non-zero exit code: error starting container: Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu compute utility]]

I have installed cuda 10.2. I can run training with tensorflow and pytorch with gpu-enabled on this machine. can someone tell wha't going on?

**Comment by vishnu2kmohan** [comment]
Hi @scotthuang1989, and welcome!

Which [installation method](https://docs.determined.ai/latest/how-to/install-main.html) did you use to install Determined? For example, did you use `det-deploy local`?

If you plan to use GPU(s), please make sure that the [Docker Engine](https://docs.determined.ai/latest/how-to/installation/docker.html?highlight=nvidia#preliminary-setup) is configured to use the [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-docker) is installed and that the Docker Engine is configured to use the NVIDIA runtime.

**Comment by scotthuang1989** [comment]
@vishnu2kmohan  thanks.  it works ok after I install Nvidia container toolkit.
